language: python
python:
    - "2.7"
before_install:
    - "export DISPLAY=:99"
    - "sh -e /etc/init.d/xvfb start"
install:
    - "pip install -e git://github.com/edx/xblock-sdk.git#egg=xblock-sdk"
    - "pip install -r $VIRTUAL_ENV/src/xblock-sdk/requirements.txt"
    - "pip install -r $VIRTUAL_ENV/src/xblock-sdk/test-requirements.txt"
    - "pip install -r requirements.txt"
    - "pip uninstall -y xblock-mentoring && python setup.py sdist && pip install dist/xblock-mentoring-2.0.tar.gz"
    - "pip install -r test_requirements.txt"
script:
    - pep8 mentoring --max-line-length=120
    - pylint mentoring --disable=all --enable=function-redefined,undefined-variable,unused-variable
    - python run_tests.py --with-coverage --cover-package=mentoring
notifications:
  email: false
branches:
    only:
        - master
